### ISSUE TITLE
[FEAT] 문화데이터 조회 기능 구현

### ISSUE THREAD

**Issue by serim53** [project-omaju/omaju-backend#11]
## 🌎 이슈 요약
문화데이터 정제 및 조회 기능 구현

<br/><br/>

## ✅ To-Do

- [x] 문화데이터 정제
- [x] 문화데이터 DB 추가
- [x] 문화생활 전체 조회 구현
- [x] 문화생활 필터링 구현
