### ISSUE TITLE
[FEAT] 산책 기능구현 필요

### ISSUE THREAD

**Issue by rigizer** [project-omaju/omaju-backend#16]
## 🌎 이슈 요약

산책 기능구현 필요

<br/><br/>

## ✅ To-Do

- [x] 산책 코스 데이터 정제
- [x] 난이도 별 산책 경로 추천
- [x] TMap OpenAPI를 이용한 도보 경로 API 구현 필요
- [x] 산책 히스토리 저장
- [x] 산책 히스토리 목록 조회
